In [1]:
stu = {'sid' :[1,2,3,4,5],
      'sname' : ['Abi','sak','anu','sahaj','babu'],
      'region' : ['n','s','e','w','g'],
      'marks' : [10,20,30,40,50]}

In [2]:
stu

{'sid': [1, 2, 3, 4, 5],
 'sname': ['Abi', 'sak', 'anu', 'sahaj', 'babu'],
 'region': ['n', 's', 'e', 'w', 'g'],
 'marks': [10, 20, 30, 40, 50]}

In [3]:
import pandas as pd
pd.DataFrame(stu)

sid  sname region  marks
0    1    Abi      n     10
1    2    sak      s     20
2    3    anu      e     30
3    4  sahaj      w     40
4    5   babu      g     50

In [4]:
match = re.finditer('\d', 'A7 b@kc 9zx')
for m in match:
    print(m.start(),'....',m.end(),'....',m.group())

NameError: name 're' is not defined

In [10]:
import urllib.request


url = 'https://www.summet.com/dmsi/html/codesamples/addresses.html'
r = urllib.request.urlopen(url)
data = r.read()
data_str = data.decode()
re.findall('\(\d{3}\) \d{3}-\d{4}', data_str)


['(257) 563-7401',
 '(372) 587-2335',
 '(786) 713-8616',
 '(793) 151-6230',
 '(492) 709-6392',
 '(654) 393-5734',
 '(404) 960-3807',
 '(314) 244-6306',
 '(947) 278-5929',
 '(684) 579-1879',
 '(389) 737-2852',
 '(660) 663-4518',
 '(608) 265-2215',
 '(959) 119-8364',
 '(468) 353-2641',
 '(248) 675-4007',
 '(939) 353-1107',
 '(570) 873-7090',
 '(302) 259-2375',
 '(717) 450-4729',
 '(453) 391-4650',
 '(559) 104-5475',
 '(387) 142-9434',
 '(516) 745-4496',
 '(326) 677-3419',
 '(746) 679-2470',
 '(455) 430-0989',
 '(490) 936-4694',
 '(985) 834-8285',
 '(662) 661-1446',
 '(802) 668-8240',
 '(477) 768-9247',
 '(791) 239-9057',
 '(832) 109-0213',
 '(837) 196-3274',
 '(268) 442-2428',
 '(850) 676-5117',
 '(861) 546-5032',
 '(176) 805-4108',
 '(715) 912-6931',
 '(993) 554-0563',
 '(357) 616-5411',
 '(121) 347-0086',
 '(304) 506-6314',
 '(425) 288-2332',
 '(145) 987-4962',
 '(187) 582-9707',
 '(750) 558-3965',
 '(492) 467-3131',
 '(774) 914-2510',
 '(888) 106-8550',
 '(539) 567-3573',
 '(693) 337-

In [17]:
sites = ['https://www.rediff.com/']
for s in sites:
    print('Searching the data from site',s)
    u = urllib.request.urlopen(s)
    text = u.read()
    title = re.findall('<title>.*</title>', str(text), re.IGNORECASE)
    print(title[0])

Searching the data from site https://www.rediff.com/
<title>Rediff.com: News | Rediffmail | Stock Quotes | Shopping</title>


In [18]:
title


['<title>Rediff.com: News | Rediffmail | Stock Quotes | Shopping</title>']

In [19]:
text

b'<!doctype html>\n<html lang="en">\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n<meta name="format-detection" content="telephone=no" />\n<meta name="viewport" content="width=device-width, initial-scale=1" />\n<title>Rediff.com: News | Rediffmail | Stock Quotes | Shopping</title>\n<meta name="keywords" content="Latest India News, Rediffmail, Live Stock Updates, Share Market Advice, Mutual Fund Quotes, Stock Quotes, Share price, Free email, Live Cricket Score, Sports News, Bollywood News, Movie Review, Rediff Money, Wealth Management, Sensex, Moneywiz, Rediffmail Login, iShare, Shopping, Business Email, Rediff, Bollywood, Bollywood Gossip, Getahead" />\n<meta name="description" content="&#10004;Read Latest India News &#10004;Get Realtime Stock Quotes &#10004;See Live Cricket Scores &#10004;Log in to Rediffmail &#10004;Buy Smart Products on Rediff Shopping" />\n<meta http-equiv="X-UA-Compatible" content="IE=Edge" />\n<link rel="alternate" media="only sc

In [5]:
import os
os.getcwd()



'C:\\Users\\abhis\\OneDrive\\Desktop\\DataScience\\ML-Edurekha\\W2'

In [6]:
os.chdir()

TypeError: chdir() missing required argument 'path' (pos 1)

In [7]:
file1 = open('Edutest.txt', 'w')
file1.write('Please write the lines \n')
file1.write('I am not scare to write the lines \n')
file1.close()


In [4]:
os.getcwd()

NameError: name 'os' is not defined

In [8]:
f = open('Edutest.txt','w')
print('File name', f.name)
print('File mode', f.mode)
print('File readable?', f.readable())
print('File writeable?', f.writable())
print('File closed?', f.closed)
f.close()
print('File closed?', f.closed)

File name Edutest.txt
File mode w
File readable? False
File writeable? True
File closed? False
File closed? True


In [12]:
f = open('Edutest.txt','a')
f.write('\nPython is open source lang')
f.write('\nPython is future')
f.close()
f = open('Edutest.txt','r')
data = f.read()
print(data)
f.close()


Python is open source lang
Python is future
Python is open source lang
Python is future
Python is open source lang
Python is future


In [1]:
pip install python-docx

  Created wheel for python-docx: filename=python_docx-0.8.10-py3-none-any.whl size=184495 sha256=9afb2ebc69c03b3536e82e4ea7e39afd014d43aca22ac67527c013f7d78b0960
  Stored in directory: c:\users\abhis\appdata\local\pip\cache\wheels\97\4c\2e\68066cbf12b9b2e66403da8982aaf4f656d9f5cb5dc3179e82
Successfully built python-docx
Note: you may need to restart the kernel to use updated packages.


In [10]:
import PyPDF2
pdfFile = open('meetingminutes.pdf', 'w')
print(pdfFile.name)
pdfFile.write('Please write the lines \n')
pdfFile.write('I am not scare to write the lines \n')
pdfFile.close()
f = open('meetingminutes.pdf','r')
data = f.read()
print(data)
f.close()

meetingminutes.pdf
Please write the lines 
I am not scare to write the lines 



In [18]:
pip install PyPDF2

  Created wheel for PyPDF2: filename=PyPDF2-1.26.0-py3-none-any.whl size=61087 sha256=67f9cf6c582b2110c1f68f63e72d6f63fd9187e0d881775535210f82f6d3d66d
  Stored in directory: c:\users\abhis\appdata\local\pip\cache\wheels\b1\1a\8f\a4c34be976825a2f7948d0fa40907598d69834f8ab5889de11
Successfully built PyPDF2
Note: you may need to restart the kernel to use updated packages.


In [13]:
f = open('TaxReturn2019.pdf','r')
data = f.read()
print(data)
f.close()

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 69: character maps to <undefined>

In [18]:
fname = input('Enter the file name')
f = open(fname, 'r')

lcount = ccount = wcount = 0 

for l in f:
    lcount = lcount + 1
    ccount = ccount + len(l)
    words = l.split()
    wcount = wcount + len(words)
print(lcount)
print(wcount)
print(ccount)

Enter the file name dict.py


44
42
600


In [22]:
import dfply

In [20]:
pip install dfply

Note: you may need to restart the kernel to use updated packages.


In [23]:
#MEan
#Median
#Mode


In [1]:
print('Hi')
try:
    print(10/0)
except Exception as e:
    print(e)
print('Hello')

Hi
division by zero
Hello


In [2]:
sales = [4544,3445,4445,3433]
profit = [543,345,445,333]
proffitratio = []
for i in range(0,len(sales)):
    proffitratio.append(profit[i]/sales[i])
print(proffitratio)

[0.11949823943661972, 0.10014513788098693, 0.10011248593925759, 0.09699970870958345]


In [7]:
import numpy as np
np.version.version

'1.18.5'

In [9]:
s_array = np.array(sales)
p_array = np.array(profit)
print(s_array)
print(p_array)
p_array/s_array

[4544 3445 4445 3433]
[543 345 445 333]


array([0.11949824, 0.10014514, 0.10011249, 0.09699971])

In [10]:
size = 10000
l1 = range(size)
l2 = range(size)

a1 = np.array(l1)
a2 = np.array(l2)

import time 
start = time.time()
result = [(x,y) for x,y in zip(l1,l2)]
print('Time taken by list  operation')
print((time.time()-start)*1000)

start = time.time()
result = a1 + a2
print('Time taken by array  operation')
print((time.time()-start)*1000)

Time taken by list  operation
32.289981842041016
Time taken by array  operation
3.5610198974609375


In [13]:
sales_us = [4322,3445,4444,3344]
sales_eu = [5433,5443,3333,2323]
sales_jp = [3322,2222,2322,2322]

In [15]:
sales_matrix = np.array([sales_us,sales_eu,sales_jp])
sales_matrix

array([[4322, 3445, 4444, 3344],
       [5433, 5443, 3333, 2323],
       [3322, 2222, 2322, 2322]])

In [17]:
sales_matrix[2,2]

2322

In [18]:
profit_us = [343,434,433,232]
profit_eu = [5433,5443,3333,2323]
profit_jp = [3322,2222,2322,2322]

In [19]:
profit_matrix = np.array([profit_us,profit_eu,profit_jp])

In [20]:
np.round(profit_matrix/sales_matrix,1)

array([[0.1, 0.1, 0.1, 0.1],
       [1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. ]])