In [1]:
dir(int)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

In [4]:
import numpy as np
np.version.version


'1.18.5'

In [11]:
a = np.array([[22,33,44,55],[11,12,23,34],[45,56,67,89]])

In [12]:
np.amin(a)

11

In [13]:
np.amax(a)

89

In [14]:
np.argmax(a)

11

In [15]:
np.argmin(a)

4

In [16]:
a

array([[22, 33, 44, 55],
       [11, 12, 23, 34],
       [45, 56, 67, 89]])

In [17]:
np.amin(a, axis=0)

array([11, 12, 23, 34])

In [18]:
np.amin(a, axis=1)

array([22, 11, 45])

In [20]:
np.amin(a, axis=-1)

array([22, 11, 45])

In [21]:
np.amax(a, axis=0)

array([45, 56, 67, 89])

In [22]:
np.amax(a, axis=1)

array([55, 34, 89])

In [23]:
print(np.mean(a,axis=1))
print(np.median(a,axis=1))

[38.5  20.   64.25]
[38.5 17.5 61.5]


In [24]:
a

array([[22, 33, 44, 55],
       [11, 12, 23, 34],
       [45, 56, 67, 89]])

In [26]:
np.sqrt(100)

10.0

In [27]:
import pandas as pd

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [34]:
stu_details = {'sid':[1,2,3,4,5],
              'sname':['A','B','C','D','E'],
              'region':['N','S','E','E','W']}

stu_marks = {'sid':[1,2,3,4,6],
            'sub':['Py','R','Py','Tab','Py'],
            'marks':[43,23,44,22,32]}

In [35]:
df1 = pd.DataFrame(stu_details)
df2 = pd.DataFrame(stu_marks)
print(df1)
print(df2)

   sid sname region
0    1     A      N
1    2     B      S
2    3     C      E
3    4     D      E
4    5     E      W
   sid  sub  marks
0    1   Py     43
1    2    R     23
2    3   Py     44
3    4  Tab     22
4    6   Py     32


In [41]:
pd.merge(df1, df2, on='sid', how='outer')

KeyError: 'self'

In [50]:
stu_details = {'s_id':[1,2,3,4,5],
              'sname':['A','B','C','D','E'],
              'region':['N','S','E','E','W']}

stu_marks = {'sid':[1,2,3,4,6],
            'sub':['Py','R','Py','Tab','Py'],
            'marks':[43,23,44,22,32]}
df1 = pd.DataFrame(stu_details)
df2 = pd.DataFrame(stu_marks)
print(df1)
print(df2)

   s_id sname region
0     1     A      N
1     2     B      S
2     3     C      E
3     4     D      E
4     5     E      W
   sid  sub  marks
0    1   Py     43
1    2    R     23
2    3   Py     44
3    4  Tab     22
4    6   Py     32


In [51]:
pd.merge(df1, df2, left_on='s_id', right_on='sid', how='outer')

s_id sname region  sid  sub  marks
0   1.0     A      N  1.0   Py   43.0
1   2.0     B      S  2.0    R   23.0
2   3.0     C      E  3.0   Py   44.0
3   4.0     D      E  4.0  Tab   22.0
4   5.0     E      W  NaN  NaN    NaN
5   NaN   NaN    NaN  6.0   Py   32.0

In [48]:
stu_details = {'s_id':[1,2,3,4,5],
              'sname':['A','B','C','D','E'],
              'region':['N','S','E','E','W']}

stu_marks = {'sid':[1,2,3,4,6],
             'sname':['A','B','C','D','E'],
            'sub':['Py','R','Py','Tab','Py'],
            'marks':[43,23,44,22,32]}

df1 = pd.DataFrame(stu_details)
df2 = pd.DataFrame(stu_marks)
print(df1)
print(df2)

pd.merge(df1, df2, left_on=['s_id','sname'], right_on=['sid','sname'], how='outer')

   s_id sname region
0     1     A      N
1     2     B      S
2     3     C      E
3     4     D      E
4     5     E      W
   sid sname  sub  marks
0    1     A   Py     43
1    2     B    R     23
2    3     C   Py     44
3    4     D  Tab     22
4    6     E   Py     32


s_id sname region  sid  sub  marks
0   1.0     A      N  1.0   Py   43.0
1   2.0     B      S  2.0    R   23.0
2   3.0     C      E  3.0   Py   44.0
3   4.0     D      E  4.0  Tab   22.0
4   5.0     E      W  NaN  NaN    NaN
5   NaN     E    NaN  6.0   Py   32.0

In [52]:
pd.merge(df1, df2, left_on='s_id', right_on='sid', how='outer')

s_id sname region  sid  sub  marks
0   1.0     A      N  1.0   Py   43.0
1   2.0     B      S  2.0    R   23.0
2   3.0     C      E  3.0   Py   44.0
3   4.0     D      E  4.0  Tab   22.0
4   5.0     E      W  NaN  NaN    NaN
5   NaN   NaN    NaN  6.0   Py   32.0

In [53]:
stu_details = {'s_id':[1,2,3,4,5],
              'sname':['A','B','C','D','E'],
              'region':['N','S','E','E','W']}

stu_marks = {'sid':[1,2,3,4,6],
             'sname':['A','B','C','D','E'],
            'sub':['Py','R','Py','Tab','Py'],
            'marks':[43,23,44,22,32]}

stu_attd = {'sid':[1,2,3,4,5,6],
           'attd':[43,23,32,43,45,43]}

df1 = pd.DataFrame(stu_details)
df2 = pd.DataFrame(stu_marks)
df3 = pd.DataFrame(stu_attd)

print(df1)
print(df2)
print(df3)


   s_id sname region
0     1     A      N
1     2     B      S
2     3     C      E
3     4     D      E
4     5     E      W
   sid sname  sub  marks
0    1     A   Py     43
1    2     B    R     23
2    3     C   Py     44
3    4     D  Tab     22
4    6     E   Py     32
   sid  attd
0    1    43
1    2    23
2    3    32
3    4    43
4    5    45
5    6    43


In [55]:
stu_details1 = {'s_id':[1,2,3,4,5],
              'sname':['A','B','C','D','E'],
              'region':['N','S','E','E','W']}

stu_details2 = {'s_id':[6,7,8,9,10],
              'sname':['P','Q','R','S','T'],
              'region':['S','N','E','E','W']}

df1 = pd.DataFrame(stu_details1)
df2 = pd.DataFrame(stu_details2)

In [56]:
df1

s_id sname region
0     1     A      N
1     2     B      S
2     3     C      E
3     4     D      E
4     5     E      W

In [57]:
df2

s_id sname region
0     6     P      S
1     7     Q      N
2     8     R      E
3     9     S      E
4    10     T      W

In [60]:
df_fin = pd.concat([df1,df2],axis=0)

In [61]:
df_fin

s_id sname region
0     1     A      N
1     2     B      S
2     3     C      E
3     4     D      E
4     5     E      W
0     6     P      S
1     7     Q      N
2     8     R      E
3     9     S      E
4    10     T      W

In [62]:
df_fin.reset_index()

index  s_id sname region
0      0     1     A      N
1      1     2     B      S
2      2     3     C      E
3      3     4     D      E
4      4     5     E      W
5      0     6     P      S
6      1     7     Q      N
7      2     8     R      E
8      3     9     S      E
9      4    10     T      W

In [65]:
import os
os.getcwd()

'C:\\Users\\abhis\\OneDrive\\Desktop\\DataScience\\ML-Edurekha\\W2'

In [66]:
BostHouse = pd.read_csv('BostonHousing.csv')

In [67]:
type(BostHouse)

pandas.core.frame.DataFrame

In [68]:
len(BostHouse)

506

In [69]:
len(BostHouse.columns)

14

In [70]:
BostHouse.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

In [74]:
BostHouse.head(14)

crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
0   0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296   
1   0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242   
2   0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2  242   
3   0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3  222   
4   0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222   
5   0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222   
6   0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311   
7   0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311   
8   0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311   
9   0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311   
10  0.22489  12.5   7.87     0  0.524  6.377   94.3  6.3467    5  311   
11  0.11747  12.5   7.87     0  0.524  6.009   82.9  6.2267    5  311   
12  0.09378  12.5   7.87     0  0.524  5.889   39.0  5.4509    5  311   
13  0.62976   0.0   8.14     0  0.538  5.949   61.8  4.7075    4  307   

    ptratio       b  lstat  medv  
0      15.3  396.90   4.98  24.0  
1      17.8  396.90   9.14  21.6  
2      17.8  392.83   4.03  34.7  
3      18.7  394.63   2.94  33.4  
4      18.7  396.90   5.33  36.2  
5      18.7  394.12   5.21  28.7  
6      15.2  395.60  12.43  22.9  
7      15.2  396.90  19.15  27.1  
8      15.2  386.63  29.93  16.5  
9      15.2  386.71  17.10  18.9  
10     15.2  392.52  20.45  15.0  
11     15.2  396.90  13.27  18.9  
12     15.2  390.50  15.71  21.7  
13     21.0  396.90   8.26  20.4

In [73]:
BostHouse.tail(5)

crim   zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
501  0.06263  0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273     21.0   
502  0.04527  0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273     21.0   
503  0.06076  0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273     21.0   
504  0.10959  0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273     21.0   
505  0.04741  0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273     21.0   

          b  lstat  medv  
501  391.99   9.67  22.4  
502  396.90   9.08  20.6  
503  396.90   5.64  23.9  
504  393.45   6.48  22.0  
505  396.90   7.88  11.9

In [75]:
BostHouse.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [76]:
BostHouse.describe()

crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677082   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio           b  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            lstat        medv  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [78]:
BostHouse[['age', 'dis', 'tax']]

age     dis  tax
0    65.2  4.0900  296
1    78.9  4.9671  242
2    61.1  4.9671  242
3    45.8  6.0622  222
4    54.2  6.0622  222
..    ...     ...  ...
501  69.1  2.4786  273
502  76.7  2.2875  273
503  91.0  2.1675  273
504  89.3  2.3889  273
505  80.8  2.5050  273

[506 rows x 3 columns]

In [79]:
BostHouse

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [82]:
BostHouse.iloc[:,[1,2,10]]

zn  indus  ptratio
0    18.0   2.31     15.3
1     0.0   7.07     17.8
2     0.0   7.07     17.8
3     0.0   2.18     18.7
4     0.0   2.18     18.7
..    ...    ...      ...
501   0.0  11.93     21.0
502   0.0  11.93     21.0
503   0.0  11.93     21.0
504   0.0  11.93     21.0
505   0.0  11.93     21.0

[506 rows x 3 columns]

In [84]:
BostHouse.iloc[:,0:3]

crim    zn  indus
0    0.00632  18.0   2.31
1    0.02731   0.0   7.07
2    0.02729   0.0   7.07
3    0.03237   0.0   2.18
4    0.06905   0.0   2.18
..       ...   ...    ...
501  0.06263   0.0  11.93
502  0.04527   0.0  11.93
503  0.06076   0.0  11.93
504  0.10959   0.0  11.93
505  0.04741   0.0  11.93

[506 rows x 3 columns]

In [86]:
BostHouse.iloc[[0,4,400], [0,3,6]]

crim  chas    age
0     0.00632     0   65.2
4     0.06905     0   54.2
400  25.04610     0  100.0

In [91]:
BostHouse[(BostHouse['rad']==2) & (BostHouse['age']>=80)].tax
#tips[(tips['sex']=='Male') & (tips['smoker']=='Yes')].total_bill

88     270
121    188
122    188
123    188
124    188
125    188
126    188
Name: tax, dtype: int64

In [92]:
BostHouse.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [93]:
BostHouse.groupby('age').size()

age
2.9       1
6.0       1
6.2       1
6.5       1
6.6       2
         ..
98.8      4
98.9      3
99.1      1
99.3      1
100.0    43
Length: 356, dtype: int64

In [95]:
BostHouse.groupby('age').agg({'ptratio':[np.mean, np.sum, np.std, np.median], 
                         'tax':[np.mean, np.sum, np.std, np.median]})

ptratio                                 tax                          
            mean    sum       std median        mean    sum         std median
age                                                                           
2.9    17.900000   17.9       NaN  17.90  233.000000    233         NaN  233.0
6.0    18.700000   18.7       NaN  18.70  398.000000    398         NaN  398.0
6.2    19.200000   19.2       NaN  19.20  305.000000    305         NaN  305.0
6.5    17.900000   17.9       NaN  17.90  233.000000    233         NaN  233.0
6.6    18.550000   37.1  0.919239  18.55  269.000000    538   50.911688  269.0
...          ...    ...       ...    ...         ...    ...         ...    ...
98.8   20.425000   81.7  0.518813  20.20  620.000000   2480  123.830529  666.0
98.9   20.533333   61.6  0.577350  20.20  589.666667   1769  132.213212  666.0
99.1   20.200000   20.2       NaN  20.20  666.000000    666         NaN  666.0
99.3   20.200000   20.2       NaN  20.20  666.000000    666         NaN  666.0
100.0  18.876744  811.7  2.535354  20.20  565.162791  24302  151.005350  666.0

[356 rows x 8 columns]

In [96]:
BostHouse.groupby(['age','tax','ptratio']).agg({'dis':[np.mean, np.sum, np.std, np.median]})

dis                           
                       mean      sum       std  median
age   tax ptratio                                     
2.9   233 17.9     5.720900   5.7209       NaN  5.7209
6.0   398 18.7     4.251500   4.2515       NaN  4.2515
6.2   305 19.2     5.287300   5.2873       NaN  5.2873
6.5   233 17.9     5.720900   5.7209       NaN  5.7209
6.6   233 17.9     5.720900   5.7209       NaN  5.7209
...                     ...      ...       ...     ...
100.0 307 21.0     4.135100   8.2702  0.056427  4.1351
      311 15.2     6.082100   6.0821       NaN  6.0821
      403 14.7     1.540557  10.7839  0.173305  1.5166
      437 21.2     1.439400   1.4394       NaN  1.4394
      666 20.2     1.540034  44.6610  0.237542  1.5331

[450 rows x 4 columns]

In [98]:
BostHouse.select_dtypes(include=['float64','int64'])

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [99]:
totaltax = BostHouse.groupby('age').tax.transform('sum')

In [100]:
totaltax

0      728
1      242
2      242
3      620
4      222
      ... 
501    273
502    577
503    939
504    273
505    580
Name: tax, Length: 506, dtype: int64

In [101]:
df = pd.DataFrame({'orderid':[1,2,3,4,5,6],
             'Manufacturer':['A','A','B','C','D','E'],
             'shipmode':['Same Day', '1st Class', '2nd Class', 'Standard Class', 'Same Day','2nd Class']})

In [102]:
df

orderid Manufacturer        shipmode
0        1            A        Same Day
1        2            A       1st Class
2        3            B       2nd Class
3        4            C  Standard Class
4        5            D        Same Day
5        6            E       2nd Class

In [107]:
from pandas.api.types import CategoricalDtype

In [108]:
type = CategoricalDtype(['Standard Class', '2nd Class', '1st Class', 'Same Day'], ordered=True)

In [105]:
df['shipmode'] = df.shipmode.astype(type)

In [106]:
df.sort_values('shipmode', ascending=True)

orderid Manufacturer        shipmode
3        4            C  Standard Class
2        3            B       2nd Class
5        6            E       2nd Class
1        2            A       1st Class
0        1            A        Same Day
4        5            D        Same Day

In [120]:
df[df.shipmode>'2nd Class']
#df.style.format(dict).bar(['Manufacture'], color='Green')

orderid Manufacturer   shipmode
0        1            A   Same Day
1        2            A  1st Class
4        5            D   Same Day

In [117]:
BostHouse.style.hide_index().set_caption('This is a Bostan House Details')

#BostHouse.style.format(dict).bar(['age'], color='Green')

In [ ]:
#BostHouse.style.format(dict).bar(['age'], color='Green')

In [121]:
df = pd.DataFrame({'orderid':[1,2,3,4,5,6],
             'Manufacturer':['A','A','B','C','D','E'],
             'shipmode':['Same Day', '1st Class', '2nd Class', 'Standard Class', 'Same Day','2nd Class']})

In [122]:
df


orderid Manufacturer        shipmode
0        1            A        Same Day
1        2            A       1st Class
2        3            B       2nd Class
3        4            C  Standard Class
4        5            D        Same Day
5        6            E       2nd Class

In [124]:
dict = {'orderid':'${:.2f}', 'Manufacture':'${:.2f}'}
#df.style.format(dict).bar(['Manufacture','shipmode'], color='Green')

In [125]:
dict

{'orderid': '${:.2f}', 'Manufacture': '${:.2f}'}

In [126]:
df.style.format(dict).highlight_max('orderid', color='green').highlight_min('orderid', color='red')

In [131]:
df.style.format(dict).bar(['orderid','Manufacture'], color='green')
df

orderid Manufacturer        shipmode
0        1            A        Same Day
1        2            A       1st Class
2        3            B       2nd Class
3        4            C  Standard Class
4        5            D        Same Day
5        6            E       2nd Class